#!/usr/bin/env bash
# extract-ims-blobs.sh — stage the QTI IMS userspace out of the stock ether zip.
#
#   ./extract-ims-blobs.sh <stock.zip> <aosp-root>
#
# WHY this is not just added to proprietary-files.txt: vendor/nextbit/ether comes from TheMuppets
# via the manifest, and TheMuppets deliberately omits the IMS set (LineageOS disabled the pre-P IMS
# stack — bullhead 5cef16f, which removed exactly one line from its blobs list). Patching a synced
# vendor repo to carry uncommittable blobs is worse than staging them, so this follows the same
# shape as the oem option: everything lands under vendor/extra, which apply-overlay clears per build.
#
# Reads proprietary-files-ims.txt beside this script. Lines are `src[:dest]`, src relative to
# system/ in the zip; dest defaults to src. See VOLTE-BRINGUP.md.
#
# The blobs are proprietary: they are staged into the tree at build time and never committed.
set -u
ZIP="${1:?usage: extract-ims-blobs.sh <stock.zip> <aosp-root>}"
AOSP="${2:?usage: extract-ims-blobs.sh <stock.zip> <aosp-root>}"
LIST="$(cd "$(dirname "$0")" && pwd)/proprietary-files-ims.txt"
[ -f "$ZIP" ]  || { echo "!! no such zip: $ZIP" >&2; exit 1; }
[ -d "$AOSP" ] || { echo "!! no such tree: $AOSP" >&2; exit 1; }
[ -f "$LIST" ] || { echo "!! missing $LIST" >&2; exit 1; }

# NOT vendor/extra: apply-overlay does "rm -rf vendor/extra" at the start of every build, so anything
# staged there before bootstrap runs is deleted at step [4/5] and the image silently ships without
# it. The oem option survives only because bootstrap runs its extractor at [4b], AFTER that clear.
# This tool is run by hand before a build, so it needs a directory nobody wipes -- and it clears its
# own, which is what the vendor/extra clear was protecting against.
DEST="$AOSP/vendor/ims-blobs"
REL="vendor/ims-blobs"
TMP="${TMPDIR:-$AOSP/out/tmp}/ims-extract.$$"
rm -rf "$DEST" "$TMP"; mkdir -p "$DEST" "$TMP" || exit 1
trap 'rm -rf "$TMP"' EXIT

echo ">> staging IMS blobs from $(basename "$ZIP")"
n=0; miss=0
: > "$TMP/copy.list"
while IFS= read -r line; do
  case "$line" in ''|\#*) continue ;; esac
  src="${line%%:*}"; dst="${line#*:}"; [ "$dst" = "$line" ] && dst="$src"
  dst="${dst%%|*}"                       # a |sha1 pin is not part of the path
  if ! unzip -q -o -j "$ZIP" "system/$src" -d "$TMP/one" 2>/dev/null; then
    echo "   !! not in zip: $src" >&2; miss=$((miss+1)); continue
  fi
  mkdir -p "$DEST/$(dirname "$dst")"
  mv "$TMP/one/$(basename "$src")" "$DEST/$dst" || { miss=$((miss+1)); continue; }
  # The destination decides the partition, not the source: only paths that are already under
  # vendor/ belong on the vendor partition. framework/, priv-app/ and etc/ are system-side, and
  # forcing them to vendor silently produces an image where the IMS jars are in a place the boot
  # classpath never looks.
  case "$dst" in
    vendor/*) echo "    $REL/$dst:\$(TARGET_COPY_OUT_VENDOR)/${dst#vendor/} \\" >> "$TMP/copy.list" ;;
    *)        echo "    $REL/$dst:\$(TARGET_COPY_OUT_SYSTEM)/$dst \\"           >> "$TMP/copy.list" ;;
  esac
  n=$((n+1))
done < "$LIST"

# PRODUCT_COPY_FILES for everything; the apks are copied verbatim too, because they are odexed
# against the 7.1 boot image and must not be re-signed or re-compiled by the build.
{
  echo "# Generated by extract-ims-blobs.sh — do not edit."
  echo "# QTI IMS userspace from the stock ether image. See VOLTE-BRINGUP.md."
  echo
  echo "PRODUCT_COPY_FILES += \\"
  sed 's|\$(TARGET_COPY_OUT_VENDOR)/vendor/|$(TARGET_COPY_OUT_VENDOR)/|' "$TMP/copy.list" | sed '$ s/ \\$//'
} > "$DEST/ims-blobs.mk"

echo ">> staged $n file(s) into $REL"
[ "$miss" -eq 0 ] || echo "!! $miss file(s) missing from the zip — the list and the image disagree" >&2
echo ">> wrote $REL/ims-blobs.mk"

# ---- libimsmedia_jni.so: the Surface allocation ------------------------------------------------
# The blob does `new Surface(...)` and baked sizeof(android::Surface) into the allocation at compile
# time. That was 3560 bytes on 7.1; on 13 it is 8168, measured at six independent `new Surface` call
# sites in the platform's own libandroid_runtime.so. libshim_vtsurface.so placement-constructs a
# modern Surface into whatever the blob allocated, so without this rewrite it overruns the heap by
# 4608 bytes and the damage lands somewhere unrelated later.
#
# The constant appears exactly once, as MOVZ x0, #3560 (00 bd 81 d2 -> 00 fd 83 d2). Search for the
# instruction rather than a fixed offset, and refuse to guess if the count is not exactly one.
for _abi in lib64; do
  _so="$DEST/vendor/$_abi/libimsmedia_jni.so"
  [ -f "$_so" ] || continue
  python3 - "$_so" <<'PYIN'
import io, sys
p = sys.argv[1]
d = bytearray(io.open(p, 'rb').read())
OLD = bytes((0xD2800000 | (3560 << 5)).to_bytes(4, 'little'))   # movz x0, #3560
NEW = bytes((0xD2800000 | (8168 << 5)).to_bytes(4, 'little'))   # movz x0, #8168
if d.count(NEW) and not d.count(OLD):
    print('   already patched'); sys.exit(0)
n = d.count(OLD)
if n != 1:
    print('!! expected exactly 1 "movz x0, #3560" in %s, found %d' % (p, n)); sys.exit(1)
i = d.index(OLD)
d[i:i+4] = NEW
io.open(p, 'wb').write(bytes(d))
print('   sizeof(Surface) 3560 -> 8168 at file offset 0x%x' % i)
PYIN
  [ $? -eq 0 ] || exit 1
done

# ---- ims.apk -----------------------------------------------------------------------------------
# Not in proprietary-files-ims.txt and not copied verbatim: stock's ims.apk is 27 KB of manifest
# with its code in an arm64 odex, and what it references -- com.android.ims -- Android 9 deleted.
# It has to be deodexed and rewritten into org.codeaurora.ims.legacy before it can run at all, which
# deodex-app.sh and rebuild-app.sh do. Built here rather than committed because it is a proprietary
# blob derived from the user's own stock image.
#
# It also cannot go in PRODUCT_COPY_FILES: AOSP rejects APKs there outright
# (build/make/core/Makefile). Hence the generated android_app_import below.
HERE="$(cd "$(dirname "$0")" && pwd)"
IMSWORK="$TMP/ims-apk"
echo ">> rebuilding ims.apk (deodex + package rename)"
if SMALI_DIR="$AOSP/prebuilts/extract-tools/common/smali" \
     "$HERE/deodex-app.sh" "$ZIP" "$IMSWORK" ims >/dev/null 2>&1 \
   && SMALI_DIR="$AOSP/prebuilts/extract-tools/common/smali" \
     "$HERE/rebuild-app.sh" "$IMSWORK" ims >/dev/null 2>&1; then
  mkdir -p "$DEST/ims"
  cp "$IMSWORK/ims-rebuilt.apk" "$DEST/ims/ims.apk" || exit 1
  cat > "$DEST/Android.bp" <<'BP'
// Generated by extract-ims-blobs.sh — do not edit.
//
// certificate "platform": ims.apk declares sharedUserId="android.uid.phone", so it must be signed
// with the platform key. It is imported unsigned and the build signs it -- never presigned.
//
// soc_specific so it lands in /vendor/app/ims, where stock put it.
//
// dex_preopt off: the apk carries a renamed copy of the 7.1 IMS framework inside its own dex, and
// preopt verification against the modern boot classpath has nothing to gain here.
android_app_import {
    name: "ims",
    apk: "ims/ims.apk",
    certificate: "platform",
    soc_specific: true,
    dex_preopt: {
        enabled: false,
    },
}
BP
  echo ">> rebuilt ims.apk -> $REL/ims/ims.apk ($(java -jar "$AOSP/prebuilts/extract-tools/common/smali/baksmali.jar" list classes <(unzip -p "$DEST/ims/ims.apk" classes.dex) 2>/dev/null | wc -l) classes)"
  echo ">> wrote $REL/Android.bp (android_app_import ims)"
else
  echo "!! ims.apk rebuild failed — VoLTE will not work; see VOLTE-BRINGUP.md" >&2
  miss=$((miss+1))
fi

[ "$miss" -eq 0 ]
